
version: '3.8'

services:
  jenkins:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    # image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # если Jenkins должен запускать docker внутри себя
    restart: unless-stopped

volumes:
  jenkins_home: 




# docker run -d \
#   --name jenkins \
#   -u root \
#   -p 8080:8080 \
#   -p 50000:50000 \
#   -v jenkins_home:/var/jenkins_home \
#   -v /var/run/docker.sock:/var/run/docker.sock \
#   jenkins/jenkins:lts